[tool.poetry]
name = "cltkv1"
version = "1.0.0"
description = "The Classical Language Toolkit"
license = "MIT"
authors = ["Kyle P. Johnson <kyle@kyle-p-johnson.com>"]
readme = "README.rst"
homepage = "http://cltk.org"
repository = "https://github.com/cltk/cltkv1"
documentation = "https://cltkv1.readthedocs.io/en/latest/"
keywords = ["nlp", "ai", "nltk", "latin", "greek"]
classifiers = [
    'Intended Audience :: Education',
    'Intended Audience :: Religion',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Natural Language :: German',
    'Natural Language :: Greek',
    'Natural Language :: Latin',
    'Natural Language :: Norwegian',
    'Operating System :: POSIX',
    'Programming Language :: Python :: 3',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'Topic :: Doc Processing',
    'Topic :: Doc Processing :: General',
    'Topic :: Doc Processing :: Linguistic',
]
#packages = [
#    { include = "cltkv1", from = "src" },
#]
#include = []
#exclude = []

[tool.poetry.dependencies]
python = "^3.7"
gitpython = "^3.0"
stanfordnlp = "^0.2.0"
isort = "^4.3"
cltk = "^0.1.112"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
nose = "^1.3"
ipython = "^7.7"
pylint = "^2.3"
sphinx = "^2.2"
coverage = "^4.5"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
pylint-json2html = "^0.1.0"
isort = "^4.3"
tox = "^3.13"
tox-pyenv = "^1.1"
pytest-cov = "^2.7"
rtd-poetry = "^0.1.0"
sphinx-autodoc-typehints = "^1.7"
pre-commit = "^1.18"
mypy = "^0.720.0"
lxml = "^4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
